# Generated by Django 3.2.8 on 2022-03-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('charges', models.IntegerField(default=1)),
                ('damage', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('heal', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.ability')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.color')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.faction')),
            ],
            options={
                'ordering': ('-color', '-damage', '-hp', '-charges'),
            },
        ),
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('damage', models.IntegerField(default=0)),
                ('charges', models.IntegerField(default=1)),
                ('passive', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='cards.ability')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='core.faction')),
            ],
            options={
                'ordering': ('faction', '-damage'),
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('health', models.IntegerField(default=0)),
                ('cards', models.ManyToManyField(related_name='cards', through='cards.CardDeck', to='cards.Card')),
                ('leader', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cards.leader')),
            ],
        ),
        migrations.AddField(
            model_name='carddeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='cards.deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.type'),
        ),
    ]
