# Generated by Django 3.2.8 on 2022-04-22 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('unlocked', models.BooleanField(default=True)),
                ('charges', models.IntegerField(default=1)),
                ('damage', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('heal', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('has_passive', models.BooleanField(default=False)),
                ('has_passive_in_hand', models.BooleanField(default=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.ability')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.color')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.faction')),
                ('passive_ability', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.passiveability')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.type')),
            ],
            options={
                'ordering': ('-color', '-damage', '-hp', '-charges'),
            },
        ),
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('health', models.IntegerField(default=0)),
                ('cards', models.ManyToManyField(related_name='cards', through='cards.CardDeck', to='cards.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('unlocked', models.BooleanField(default=True)),
                ('damage', models.IntegerField(default=0)),
                ('charges', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('has_passive', models.BooleanField(default=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='core.ability')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='core.faction')),
                ('passive_ability', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='core.passiveability')),
            ],
            options={
                'ordering': ('faction', '-damage'),
            },
        ),
        migrations.CreateModel(
            name='UserLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_l', to='cards.leader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_l', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_d', to='cards.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_d', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_c', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_c', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cards.leader'),
        ),
        migrations.AddField(
            model_name='carddeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='cards.deck'),
        ),
    ]
