# Generated by Django 3.2.8 on 2022-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
