# Generated by Django 3.2.8 on 2022-04-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='passive',
            new_name='has_passive',
        ),
        migrations.AddField(
            model_name='card',
            name='has_passive',
            field=models.BooleanField(default=False),
        ),
    ]
