# Generated by Django 3.2.8 on 2022-10-16 08:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_card_timer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together={('card', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userdeck',
            unique_together={('deck', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userleader',
            unique_together={('leader', 'user')},
        ),
    ]
