# Generated by Django 3.2.8 on 2021-12-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_ability_color_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='dmg_one',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='heal',
        ),
    ]
