# Generated by Django 3.2.8 on 2021-12-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20211217_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('damage', models.IntegerField(default=0)),
                ('heal', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.ability')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.color')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.faction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.type')),
            ],
        ),
    ]
