# Generated by Django 3.2.8 on 2022-04-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_passiveability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passiveability',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
