# Generated by Django 3.2.8 on 2022-04-02 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_passiveability_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='passive_ability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.passiveability'),
        ),
        migrations.AddField(
            model_name='leader',
            name='passive_ability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='cards.passiveability'),
        ),
    ]
