# Generated by Django 3.2.8 on 2021-12-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='charges',
            field=models.IntegerField(default=1),
        ),
    ]
