# Generated by Django 3.2.8 on 2022-12-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_leader_heal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdeck',
            options={'ordering': ['-deck__updated_at']},
        ),
        migrations.AddField(
            model_name='deck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
