# Generated by Django 3.2.8 on 2021-12-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='hp',
            field=models.IntegerField(default=0),
        ),
    ]
