# Generated by Django 3.2.8 on 2022-12-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20221202_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='each_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='has_passive_in_deck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='has_passive_in_grave',
            field=models.BooleanField(default=False),
        ),
    ]
