# Generated by Django 3.2.8 on 2022-04-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20220418_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='locked',
            new_name='unlocked',
        ),
        migrations.RenameField(
            model_name='leader',
            old_name='locked',
            new_name='unlocked',
        ),
    ]
