# Generated by Django 3.2.8 on 2022-04-20 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_ability_enemyleaderability_enemypassiveability_move_passiveability_type'),
        ('cards', '0007_auto_20220418_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.ability'),
        ),
        migrations.AlterField(
            model_name='card',
            name='passive_ability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.passiveability'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.type'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='core.ability'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='passive_ability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='core.passiveability'),
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
        migrations.DeleteModel(
            name='PassiveAbility',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='usercard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='cards.card'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together={('card_id', 'user_id')},
        ),
    ]
