# Generated by Django 3.2.8 on 2021-12-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_try'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('cards', models.ManyToManyField(related_name='cards', through='cards.CardDeck', to='cards.Card')),
            ],
        ),
        migrations.AddField(
            model_name='carddeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='d', to='cards.deck'),
        ),
    ]
