# Generated by Django 3.2.8 on 2021-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20211218_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='health',
            field=models.IntegerField(default=0),
        ),
    ]
