# Generated by Django 3.2.8 on 2022-04-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20220420_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='has_passive_in_hand',
            field=models.BooleanField(default=False),
        ),
    ]
