# Generated by Django 3.2.8 on 2021-12-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_deck_health'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
    ]
