# Generated by Django 3.2.8 on 2021-12-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_delete_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddeck',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='cards.card'),
        ),
        migrations.AlterField(
            model_name='carddeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='cards.deck'),
        ),
    ]
