# Generated by Django 3.2.8 on 2021-12-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20211221_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('damage', models.IntegerField(default=0)),
                ('charges', models.IntegerField(default=1)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leaders', to='cards.ability')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='cards.faction')),
            ],
        ),
    ]
