# Generated by Django 3.2.8 on 2021-12-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cards.leader'),
            preserve_default=False,
        ),
    ]
