# Generated by Django 3.2.8 on 2022-01-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20220116_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='description',
        ),
        migrations.AddField(
            model_name='ability',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
