# Generated by Django 3.2.8 on 2022-01-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_auto_20220116_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cards.leader'),
        ),
    ]
