# Generated by Django 3.2.8 on 2022-01-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_alter_deck_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cards.leader'),
        ),
    ]
