# Generated by Django 3.2.8 on 2022-02-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_alter_deck_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
