# Generated by Django 3.2.8 on 2022-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
    ]
