# Generated by Django 3.2.8 on 2022-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0020_leader_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('-color', '-damage', '-hp', '-charges')},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ('faction', '-damage')},
        ),
    ]
