# Generated by Django 3.2.8 on 2022-11-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deathwish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'abilities'},
        ),
        migrations.AlterModelOptions(
            name='deathwish',
            options={'verbose_name_plural': 'deathwishes'},
        ),
        migrations.AlterModelOptions(
            name='enemyleaderability',
            options={'verbose_name_plural': 'enemy leader abilities'},
        ),
        migrations.AlterModelOptions(
            name='enemypassiveability',
            options={'verbose_name_plural': 'enemy passive abilities'},
        ),
        migrations.AlterModelOptions(
            name='passiveability',
            options={'verbose_name_plural': 'passive abilities'},
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
