# Generated by Django 3.2.8 on 2022-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220428_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='keys',
            field=models.IntegerField(default=3),
        ),
    ]
