# Generated by Django 3.2.8 on 2022-04-18 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20220418_1319'),
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='u', to='cards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='u', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='cards',
            field=models.ManyToManyField(related_name='cards_users', through='accounts.CardUser', to='cards.Card'),
        ),
    ]
