# Generated by Django 3.2.8 on 2022-04-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20220420_1204'),
        ('accounts', '0004_auto_20220418_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cards',
            field=models.ManyToManyField(related_name='user_cards', through='cards.UserCard', to='cards.Card'),
        ),
        migrations.DeleteModel(
            name='CardUser',
        ),
    ]
