# Generated by Django 3.2.8 on 2022-04-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20220420_1343'),
        ('accounts', '0005_auto_20220420_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='decks',
            field=models.ManyToManyField(related_name='user_decks', through='cards.UserDeck', to='cards.Deck'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='leaders',
            field=models.ManyToManyField(related_name='user_leaders', through='cards.UserLeader', to='cards.Leader'),
        ),
    ]
