# Generated by Django 3.2.8 on 2022-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0007_auto_20220421_1306'),
        ('accounts', '0006_auto_20220420_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='levels',
            field=models.ManyToManyField(related_name='user_levels', through='enemies.UserLevel', to='enemies.Level'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='resource',
            field=models.IntegerField(default=1000),
        ),
    ]
