# Generated by Django 3.2.8 on 2022-04-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('damage', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='enemies/')),
                ('shield', models.BooleanField(default=False)),
                ('has_passive', models.BooleanField(default=False)),
                ('passive_increase_damage', models.IntegerField(default=0)),
                ('passive_heal', models.IntegerField(default=0)),
                ('passive_heal_leader', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enemies', to='core.color')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enemies', to='core.faction')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enemies', to='core.move')),
                ('passive_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enemies', to='core.enemypassiveability')),
            ],
        ),
        migrations.CreateModel(
            name='EnemyLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='enemy_leaders/')),
                ('has_passive', models.BooleanField(default=False)),
                ('hp', models.IntegerField(default=0)),
                ('damage_once', models.IntegerField(blank=True, default=0, null=True)),
                ('damage_per_turn', models.IntegerField(blank=True, default=0, null=True)),
                ('heal_self_per_turn', models.IntegerField(blank=True, default=0, null=True)),
                ('ability', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enemy_leaders', to='core.enemyleaderability')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enemy_leaders', to='core.faction')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('starting_enemies_number', models.IntegerField(default=3)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], max_length=20)),
                ('unlocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_level', to='enemies.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_level', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LevelEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l', to='enemies.enemy')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l', to='enemies.level')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='enemies',
            field=models.ManyToManyField(related_name='levels', through='enemies.LevelEnemy', to='enemies.Enemy'),
        ),
        migrations.AddField(
            model_name='level',
            name='enemy_leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='enemies.enemyleader'),
        ),
    ]
