# Generated by Django 3.2.8 on 2022-02-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_auto_20220219_1615'),
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyLeaderAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='move',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EnemyLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='enemy_leaders/')),
                ('hp', models.IntegerField(default=0)),
                ('passive', models.BooleanField(default=False)),
                ('damage', models.IntegerField(default=0)),
                ('damage_per_turn', models.IntegerField(default=0)),
                ('heal_self_per_turn', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enemy_leaders', to='cards.faction')),
            ],
        ),
    ]
