# Generated by Django 3.2.8 on 2022-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='related_levels',
            field=models.ManyToManyField(blank=True, null=True, to='enemies.Level'),
        ),
    ]
