# Generated by Django 3.2.8 on 2022-02-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0002_auto_20220219_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemyleader',
            old_name='damage',
            new_name='damage_once',
        ),
    ]
