# Generated by Django 3.2.8 on 2022-09-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0002_level_related_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
