# Generated by Django 3.2.8 on 2022-02-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0003_rename_damage_enemyleader_damage_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemyleader',
            name='ability',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enemy_leaders', to='enemies.enemyleaderability'),
        ),
        migrations.AlterField(
            model_name='enemyleader',
            name='damage_once',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enemyleader',
            name='damage_per_turn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enemyleader',
            name='heal_self_per_turn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
