# Generated by Django 3.2.8 on 2022-04-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0003_auto_20220402_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='passive_ability_id',
            new_name='passive_ability',
        ),
    ]
