# Generated by Django 3.2.8 on 2022-09-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0003_userlevel_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='related_levels',
            field=models.ManyToManyField(blank=True, to='enemies.Level'),
        ),
    ]
