# Generated by Django 3.2.8 on 2022-10-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0004_alter_level_related_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s1', to='enemies.level')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('levels', models.ManyToManyField(related_name='seasons', through='enemies.LevelSeason', to='enemies.Level')),
            ],
        ),
        migrations.AddField(
            model_name='levelseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s2', to='enemies.season'),
        ),
    ]
