# Generated by Django 3.2.8 on 2022-02-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0004_auto_20220219_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='enemy_leader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='enemies.enemyleader'),
        ),
    ]
