# Generated by Django 3.2.8 on 2022-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0005_auto_20220420_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='passive',
            new_name='has_passive',
        ),
        migrations.RenameField(
            model_name='enemyleader',
            old_name='passive',
            new_name='has_passive',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='passive_damage',
        ),
    ]
