# Generated by Django 3.2.8 on 2022-10-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0005_auto_20221022_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='related_levels',
        ),
    ]
