# Generated by Django 3.2.8 on 2022-10-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0006_remove_level_related_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRelatedLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(choices=[('down', 'down'), ('up', 'up'), ('right', 'right'), ('left', 'left')], max_length=16)),
                ('connection', models.CharField(max_length=16)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l1', to='enemies.level')),
                ('related_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l2', to='enemies.level')),
            ],
            options={
                'unique_together': {('level', 'related_level')},
            },
        ),
        migrations.AddField(
            model_name='level',
            name='related_levels',
            field=models.ManyToManyField(related_name='_enemies_level_related_levels_+', through='enemies.LevelRelatedLevels', to='enemies.Level'),
        ),
    ]
