# Generated by Django 3.2.8 on 2022-10-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0008_auto_20221022_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='enemies.season'),
        ),
    ]
