# Generated by Django 3.2.8 on 2022-10-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0009_level_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
