# Generated by Django 3.2.8 on 2022-10-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0010_auto_20221022_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='related_levels',
            field=models.ManyToManyField(related_name='rel_levels', through='enemies.LevelRelatedLevels', to='enemies.Level'),
        ),
    ]
