# Generated by Django 3.2.8 on 2022-11-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deathwish'),
        ('enemies', '0012_auto_20221024_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='deathwish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enemies', to='core.deathwish'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='has_deathwish',
            field=models.BooleanField(default=False),
        ),
    ]
