# Generated by Django 3.2.8 on 2022-11-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0013_auto_20221108_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enemy',
            options={'verbose_name_plural': 'enemies'},
        ),
    ]
