# Generated by Django 3.2.8 on 2022-11-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0014_alter_enemy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='passive_heal',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='passive_heal_leader',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='passive_increase_damage',
        ),
    ]
