# Generated by Django 3.2.8 on 2022-11-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0016_auto_20221129_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemyleader',
            name='base_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemyleader',
            name='default_timer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemyleader',
            name='reset_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemyleader',
            name='timer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enemyleader',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
