# Generated by Django 3.2.8 on 2022-12-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0017_auto_20221130_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='each_tick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemy',
            name='has_passive_in_deck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemy',
            name='has_passive_in_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemy',
            name='has_passive_in_grave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enemyleader',
            name='each_tick',
            field=models.BooleanField(default=False),
        ),
    ]
