# Generated by Django 3.2.8 on 2023-01-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221128_0908'),
        ('enemies', '0018_auto_20221226_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemyleader',
            name='damage_once',
        ),
        migrations.RemoveField(
            model_name='enemyleader',
            name='damage_per_turn',
        ),
        migrations.RemoveField(
            model_name='enemyleader',
            name='heal_self_per_turn',
        ),
        migrations.AddField(
            model_name='enemyleader',
            name='passive_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enemy_leaders', to='core.enemypassiveability'),
        ),
    ]
