name: ci-cd

on:
  pull_request:
    branches: [ dev, master ]
  push:
    branches: [ dev, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MODE: ${{ github.ref_name == 'master' && 'prod' || 'dev' }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements-dev.txt

      - name: Lint with flake8
        run: cd backend && flake8 .

      - name: Check imports ordering with isort
        run: cd backend && isort -c .

      - name: test with Pytest
        run: pytest